[package]
name = "HTMLIcedRenderer"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.12", features = ["tokio", "image"] }
kuchiki = "0.8"
reqwest = { version = "0.11", features = ["blocking"] }
